### ISSUE TITLE
Feature Enhancement on object : Scaling and bring front/back

### ISSUE THREAD

**Issue by smalldragoon** [Dojibery/flutter-advanced-canvas-editor#5]
Hi, 
For the "icons" ( the car ) , you can rotate / delete. 

I suggest scaling would be a very good action as well 
I suggest ordering the object front/backward would be a very good action as well

Happy to discuss further of course and help if I can ( not beeing a great dev ...) 
Thanks !

**Comment by vlladislav45** [comment]
Thanks for your suggestion @smalldragoon . I will pay attention on this one

**Comment by smalldragoon** [comment]
Great, Thanks !!
Do you have like a "roadmap" ?

**Comment by vlladislav45** [comment]
https://github.com/Dojibery/flutter-advanced-canvas-editor/pull/6 @smalldragoon . Here you go

**Comment by vlladislav45** [comment]
Closing the issue, PR has been merged
